# Python & Pandas Introduction
## Python/Jupyter Installation Instructions
First, make sure you have python3 (version 3.7 is the latest) installed on your local machine.
We recommend managing your python installation with Anaconda.
The Anaconda website has instructions for how to install python based on your operating system:
- https://www.anaconda.com/download/

Second, make sure that you have Jupyter notebooks installed.
It may have already come with your Anaconda installation.
If not, the Jupyter website has installation instructions:
- http://jupyter.org/install

If you have never used python or Jupyter notebooks before, we recommend bookmarking these resources:
- Python: https://developers.google.com/edu/python/
- Jupyter: https://www.datacamp.com/community/tutorials/tutorial-jupyter-notebook

Be aware that the Google tutorial uses python2, so some of their example code may not directly work in python3:
- Print statements now require parentheses: `print x` now becomes `print(x)`
- No longer need to specify file encoding: `open('file.txt', 'r')` works
- The division operator `/` no longer does integer divison: `5 / 2` is `2.5`
- The `xrange` operator is now only `range`

Other differences can be found on the web: https://www.geeksforgeeks.org/important-differences-between-python-2-x-and-python-3-x-with-examples/


## About Python
Python is a programming language that is very popular among the machine learning research community.
It is a higher-level programming language than Java, and has an extensive collection of libraries that can be easily installed.
We require that you use python for this class, so it is important to be familiar with it.

### Python vs Java
- Java is compiled, but Python is not: you directly run the Python file
- Java is statically typed (the types of the variables cannot change), and you do not declare types in Python
```
# This works in python
x = 3
x = "python"
```
- Instantiating a class in Python does not use `new`
```
# Assume there is a class called `Person`
p = Person('Emily', 25)
```
- Python does not use parentheses, like Java. Instead, it uses whitespace to infer the scope of methods, for loops, etc.
```
for i in range(10):
      print(i * 2)      # Indent by 4 spaces
      print(i * 4)
print('Done')       # No indent, runs after for loop
```
- Functions cannot be overloaded, instead use optional arguments
```
def f(x, y=0.0):
      ....
f(8)
f(8, 2)
```
- Boolean values are now `True` and `False`

### Python vs Matlab
- Python uses hard brackets `[]` for indexing arrays and matrices instead of `()` in Matlab
- Python is 0-indexed, so the first item in a list is at index 0, not 1
- Python doesn't come by default with a full development tool, like Matlab
- The `numpy` library in Python implements many of the same matrix functionality that Matlab has

### Development Environments
- In this class we will use Jupyter Notebooks, which is one of many ways you can write python code. We feel that Jupyter Notebooks are a simple, but effective tool.
- Other options include:
  - Text editors: Atom, Sublime
  - PyCharm: https://www.jetbrains.com/pycharm/
  - Google Collaboratory: https://colab.research.google.com/ 



## Jupyter Notebooks
When you start a Jupyter Notebook, you are starting a server on your local machine that hosts the notebooks.
```
> jupyter notebook
```
Once the server has started, open up a web browser and go to http://localhost:8888.
You should see a file tree, which you can use to navigate to where you want to save your Jupyter Notebook.

Jupyter Notebooks allow you to interactively develop python code.
Cells have types, either markdown (https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet) or python code.
You can write as much code in a cell as you need.
When you want to execute it, enter shift+enter.
Anything displayed by your program will be written below the cell.
Variables that are defined within an executed cell are saved in memory and can be used later (similar behavior in Matlab).
It's similar to if you could pause the program execution.
Code within other cells can reference any cell _which has already been executed_.
If you have already run a cell and you edit its code, the cell needs to be rerun in order for your changes to take effect.

If you close the Jupyter Notebook, you will need to rerun all of the cells from scratch so the variables and methods will be redefined. **Make sure you save before you close the notebook!**

### Submitting assignments
Your Jupyter Notebook can be downloaded as a python file that can be run under File -> Download -> Python .py.
You should turn in this python file and **not** the `.ipynb` file.

### Basics

In [ ]:
# Assigning variables
x = 4.2
y = 8
s = 'hello'

# The types of variables can change without a problem
y = 'abc'

# To display variables, use the print function
print(y)

# The "null" type is called `None`
z = None
print(z)

print(z == None)

# Casting
s = '140'
print(int(s))
s = '140.243'
print(float(s))
x = 123
print(str(x))

abc
None
True
140
140.243
123


### String Manipulation

In [ ]:
s = "ABCdef"
s = 'ABCdef'

# Length
print(len(s))  # 6

# Standard Indexing: Notice hard brackets and 0-indexing
print(s[0])      # 'A'
print(s[1])      # 'B'
print(s[5])      # 'f'
# print(s[100])  # Error

# Range Indexing
print(s[1:4])    # 'BCd'
print(s[2:])     # 'Cdef'
print(s[:2])     # 'AB'
print(s[1:100])  # 'BCdef'

# Negative Indexing
print(s[-1])    # 'f'
print(s[-2])    # 'e'
print(s[:-1])   # 'ABCde'
print(s[:-3])   # 'ABC'
print(s[::-1])  # 'fedCBA'

# Concatenation
print(s + 'xyz')     # 'ABCdefxyz'
# print(s + 123)     # Error
print(s + str(123))  # 'ABCdef123'

# Splitting
print(s.split('C'))  # ['AB', 'def']

6
A
B
f
BCd
Cdef
AB
BCdef
f
e
ABCde
ABC
fedCBA
ABCdefxyz
ABCdef123
['AB', 'def']


### Lists

In [ ]:
a = [0, 4, 2, 8, 9]  # Create a list with initial items
b = []  # Create an empty list

# Length
print(len(a))  # 5

# The same indexing operations on strings work for lists
print(a[1])    # 4
print(a[2:4])  # [2, 8]
print(a[-2])   # 8

# Sort the list
print(sorted(a))                # [0, 2, 4, 8, 9] Creates a copy, does not modify the original list
print(sorted(a, reverse=True))  # [9, 8, 4, 2, 0] Also a copy

# Add items to the end of the list
a.append(10)  # Returns nothing
print(a)      # [0, 4, 2, 8, 9, 10] 
a += [1, 12]  # Returns nothing
print(a)      # [0, 4, 2, 8, 9, 10, 1, 12]

# Lists don't have to be the same type in python
a.append('machine learning')
print(a)            # [0, 4, 2, 8, 9, 10, 1, 12, 'machine learning']
# print(sorted(a))  # Causes an error

# Searching
print(8 in a)    # True
print(100 in a)  # False

## Dictionaries
https://developers.google.com/edu/python/dict-files

In [ ]:
d = {'b':3}       # Create an empty dictionary, which is a key-value map
d['a'] = 97  # Add an item to the dictionary
print(d)     # {'a': 97}
print(d['a'])

d['c'] = 99
d[0] = [0, 1, 2]  # Keys and values don't need to be the same type
print(d)          # {'a': 97, 'c': 99, 0: [0, 1, 2]}

# Retrieve the keys and values of the dictionary.
# These are not actually lists, but look like it. Call list(d.keys()) to actually convert it to a list
keys = d.keys()      # Retrieve a list of the keys of the dictionary, not necessarily in any order
values = d.values()  # Retrieve a list of the values of the dictionary, not necessarily in any order
print(keys)          # ['a', 'c', 0]
print(values)        # [97, 99, [0, 1, 2]]

# Check to see if items are in the dictionary (checks keys)
print('a' in d)  # True
print('x' in d)  # False

# Remove an item from the list
del d['a']    # Returns nothing, modifies inplace
# del d['y']  # Error

## If Statements
Covered in the strings section: https://developers.google.com/edu/python/strings

In [ ]:
# Python doesn't require parenthese
a, b = 7, 10

# equality
if a == 7:
    print('yes')
else:
    print('no')
    
# not equal
if a != 8:
    print('neq')
    
# and
if a > 5 and b <= 10:
    print('1')
elif a > 10:
    print('2')
else:
    print('3')

# or
if a < 10 or b > 100:
    print('yes')
    
# Strings also use '=='
s = 'abc'
if s == 'abc':
    print('here')

## For Loops
Covered under lists: https://developers.google.com/edu/python/lists

In [ ]:
a = [0, 8, 3, 5, 1]

range(5)     # Dynamically generates 0, 1, 2, 3, 4
range(1, 5)  # 1, 2, 3, 4

# "Standard" for loop from Java
for i in range(len(a)):
    print(a[i])

# Iterate over each element in the list
for x in a:
    print(x)
    
# Iterating through dictionaries
d = {0: 'a', 1: 'b', 2: 'c'}
for key, value in d.items():
    print(str(key) + ' -> ' + value)
    
    
# Loop over items in an array and get the index at the same time
for index, item in enumerate(a):
  print(index, item)

## Methods

In [ ]:
# No return type specification necessary
def add(x, y):
    return x + y

def concat(list_1, list_2):
    list_1 += list_2

print(add(3, 4))        # 7
# print(add(4, 8, 10))  # Error

# Arguments can be passed by name
print(add(y=8, x=2))  # 10

a1 = [0, 1]
a2 = [3, 5]
concat(a1, a2)  # Returns nothing
print(a1)       # [0, 1, 3, 5]

# Methods can return more than one thing
def two(a):
  return a + 1, a + 2

a3, a4 = two(1)
print(a3)  # 2
print(a4)  # 3

t = two(1)
print(t[0])
print(t[1])

## List and Dictionary Comprehension

In [ ]:
# Sometimes code can be simplified using list/dictionary comprehensions
def add_one(x):
  return x + 1

# The standard way to apply a function to every element and save in y
x = [0, 1, 2, 3]
y = []
for i in range(len(x)):
  y.append(add_one(x[i]))

# This is equivalent to the above
y = [add_one(x_i) for x_i in x]

# Add conditionals
y2 = [add_one(x_i) for x_i in x if x_i > 1]

# Dictionary comprehensions can be used to create dictionaries easily.
# This creates a mapping from x_i -> x_i * 4
d = {x_i : x_i * 4 for x_i in x}
print(d)
print(d[2])  # 8

## Files
https://developers.google.com/edu/python/dict-files

In [ ]:
# Reading from a file
# In the same directory as the Jupyter notebook is a file called 'input.txt'.
# You can use this for loop template to iteratively read a file line by line. Generally, you will
# include some parsing logic to extract data from each line
lines = []
with open('input.txt', 'r') as f:   # This is the line which opens the file. `f` is the file handler
                                    # The `with open` will automatically close the file are you are done reading.
                                    # 'r' means you want to read from the file
    for line in f:
        line = line.strip()         # `strip()` removes any  whitespace from the beginning and end of the string
                                    # By default, each line will have '\n' at the end. 
        upper = line.upper()        # Here is where you would add your custom parsing logic
        lines.append(upper)

print(lines)  # ['A', 'B', 'C', 'D', 'E', 'F', 'G']

# Writing to a file
# This will write each of the apital letters to a line in an output file
out = open('out.txt', 'w')
out.write('hi')
out.close()

with open('output.txt', 'w') as out:  # 'w' means you want to write to the file. This will overwite the file if it exists
    for item in lines:
        out.write(str(item) + '\n')   # the `write` method only accepts strings and you have to
                                      # manually take care of the '\n' yourself

### Classes

In [ ]:
class Person(object):
    # This is the constructor. All instance methods of a class
    # must accept `self` as the first parameter
    # The self parameter is a reference to the current instance of the class, and is used to access variables that belongs to the class
    # You use `self` to access data members and methods of the class,
    # similar to `this` in Java
    def __init__(self, name, age):
        # This will call the super class's constructor; Optional if you inherit from `object`
        super().__init__()
        
        # Assign data members
        self.name = name
        self.age = age
        
    def is_adult(self):
        return self.age >= 18
    
    def is_child(self):
        # Other instance methods are called with the `self` keyword.
        return not self.is_adult()
    
    def increment_age(self, amount):
        self.age += amount
        
    # Test to see if two `Person` objects are equal
    def __eq__(self, other):
        return self.name == other.name and self.age == other.age

In [ ]:
p = Person('Bob', 19)

# Data members can be accessed directly
print(p.name)  # 'Bob'
print(p.age)   # 19

# Even though all of the methods require a `self` argument, you ignore that argument
# when calling the method
print(p.is_adult())  # True 

p.increment_age(1)  # Returns nothing
print(p.age)        # 20

p2 = Person('Mary', 30)
print(p == p2)  # False

p3 = Person('Mary', 30)
print(p2 == p3)  # True

Bob
19
True
20
False
True


# Useful Packages
There are many packages that come with your python installation as well as many which can be downloaded easily for free.
Importing a package requires the `import` command.
Most packages can be installed using the `pip` command (which is run on the command line, not within a python environment), that is included with the python installation.

```
> pip install numpy
> pip install scikit-learn
```


### random
The `random` package provides tools for generating random numbers.

In [ ]:
import random

random.seed(4)

print(random.randint(1, 5))  # A random integer in (1, 5)

print(random.random())  # A random number in (0, 1.0]

# Randomly shuffle a list
a = [0, 1, 2, 3, 4, 5]
random.shuffle(a)  # Shuffles in place - does not return a copy
print(a)

### numpy
`numpy` is a very useful matrix library for Python.
It is used very frequently in machine learning, so it is good to be familiar with it.
If your program crashes with an import error when you import numpy, you need to install it with
```
> pip install numpy
```

In [ ]:
# Imports can be aliased to simplify code
import numpy as np  # The numpy library is now referenced with np

# Create a vector of length 5 of all 0s
v = np.zeros(5)
print(v)

print(v.shape)     # Returns a tuple of the dimensions: (5,)
print(v.shape[0])  # Returns the size of the 0th dimension, 5

# You can assign specific entries by their index into the vector
v[0] = 1
v[1] = 4

# You can assign ranges of values
v[2:5] = [5, 3, 6]
print(v)

# Create a random vector of values between 0 and 1
np.random.seed(1)
v1 = np.random.rand(5)
print(v1)

# Compute the dot product
print(np.dot(v, v1))

# Element-wise multiplication
print(v * v1)
print(np.multiply(v, v1))  # equivalent

# Multiply the whole vector by a scalar, add a constant
print(v * 5)
print(v + 3)

[0. 0. 0. 0. 0.]
(5,)
5
[1. 4. 5. 3. 6.]
[4.17022005e-01 7.20324493e-01 1.14374817e-04 3.02332573e-01
 1.46755891e-01]
5.086424915356129
[4.17022005e-01 2.88129797e+00 5.71874087e-04 9.06997718e-01
 8.80535345e-01]
[4.17022005e-01 2.88129797e+00 5.71874087e-04 9.06997718e-01
 8.80535345e-01]
[ 5. 20. 25. 15. 30.]
[4. 7. 8. 6. 9.]


In [ ]:
# Matrices work much the same way (vectors are just matrices with 1 dimension)
# `np.ones` creates a matrix of the given input size
t = (3, 4)
X = np.ones(t)
print(X)
print(X.shape)     # (3, 4)
print(X.shape[0])  # 3
print(X.shape[1])  # 4

# Assigning specific entries requires 2 indices
# The first is the row index, the second is the column index
X[1, 3] = 8
print(X)

# The `:` selects the entire row or column
row1 = X[1, :]
print(row1)
print(X[:, 2])

# It can also be used to assign values
X[1, :] = [1, 2, 3, 4]
print(X)

# Matrix multiplication
Y = np.random.rand(4, 5)
print(np.matmul(X, Y))  # A matrix of size (3, 5)

# Transpose
print(X.transpose())
print(X.T)  # equivalent

# You can create a matrix from a list (of lists)
Z = np.asarray(
    [
        [0, 1, 2], 
        [3, 4, 5]
    ])
print(Z)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
(3, 4)
3
4
[[1. 1. 1. 1.]
 [1. 1. 1. 8.]
 [1. 1. 1. 1.]]
[1. 1. 1. 8.]
[1. 1. 1.]
[[1. 1. 1. 1.]
 [1. 2. 3. 4.]
 [1. 1. 1. 1.]]
[[1.98274519 2.25704609 1.42212698 2.10759446 1.64069497]
 [6.14510843 6.68165992 3.68423142 5.34345363 4.693453  ]
 [1.98274519 2.25704609 1.42212698 2.10759446 1.64069497]]
[[1. 1. 1.]
 [1. 2. 1.]
 [1. 3. 1.]
 [1. 4. 1.]]
[[1. 1. 1.]
 [1. 2. 1.]
 [1. 3. 1.]
 [1. 4. 1.]]
[[0 1 2]
 [3 4 5]]


In [ ]:
# Useful ways to initialize matrices
A = np.zeros((5, 3))  # A 5x5 matrix of all 0s
print(A)

A = np.ones((5, 3))  # A 5x3 matrix of all 1s
print(A)

A = np.eye(5)  # I matrix of size 5x5
print(A)

A = np.random.rand(5, 3)  # A random matrix of size 5x3 with numbers between 0 and 1
print(A)

A = np.random.randint(1, 4, (5, 3)) # A random matrix of integers in (0, 4] of size 5x3
print(A)


### sklearn
`sklearn` is a useful machine learning library. It can be installed with
```
> pip install scikit-learn
```

In [ ]:
# An example learning problem. You may use this as a template for homework
from sklearn.linear_model import SGDClassifier

# This is the feature matrix. There are 7 rows (7 training examples) with
# 4 columns (4 features).
X = np.asarray(
[
    [0, 0, 1, 0],
    [0, 1, 0, 0],
    [0, 0, 1, 1],
    [1, 0, 0, 1],
    [0, 1, 1, 0],
    [1, 1, 0, 0],
    [0, 1, 0, 1]
])

# These are the binary class labels for all 7 instances
y = np.asarray([0, 0, 1, 1, 0, 0, 0])

# Create the classifier
clf = SGDClassifier(loss="hinge", penalty="l2")

# Train the classifier on our labeled data
clf.fit(X, y)

# Use our trained classifier to predict labels for new input data
X_test = np.asarray(
[
    [1, 0, 0, 0],
    [0, 1, 1, 1],
    [0, 0, 0, 1]
])
y_pred = clf.predict(X_test)

# Let's assume we know the actual labels of `X_test` are this
y_test = np.array([0, 1, 1])

# We can compute the total number of correct classifications:
num_correct = sum(y_pred == y_test)
total = y_pred.shape[0]
print('Accuracy: ' + str(num_correct / total * 100))

Accuracy: 66.66666666666666


# Pandas Topics

In [ ]:
import pandas as pd
import numpy as np

# !pip install jupyter_contib_nbextensions

## Series & DataFrames

In [ ]:
sports = pd.Series(['football', 'basketball',' volleyball','tennis'])

population = pd.Series({'Germany': 81.3, 'Belgium': 11.3, 'France': 64.3, 
                        'United Kingdom': 64.9, 'Netherlands': 16.9})

countries = pd.DataFrame({'country': ['Belgium', 'France', 'Germany', 'Netherlands', 'United Kingdom'],
        'population': [11.3, 64.3, 81.3, 16.9, 64.9],
        'area': [30510, 671308, 357050, 41526, 244820],
        'capital': ['Brussels', 'Paris', 'Berlin', 'Amsterdam', 'London']})

In [ ]:
sports

In [ ]:
population

Germany           81.3
Belgium           11.3
France            64.3
United Kingdom    64.9
Netherlands       16.9
dtype: float64

In [ ]:
countries

country  population    area    capital
0         Belgium        11.3   30510   Brussels
1          France        64.3  671308      Paris
2         Germany        81.3  357050     Berlin
3     Netherlands        16.9   41526  Amsterdam
4  United Kingdom        64.9  244820     London

In [ ]:
type(population)

In [ ]:
sports.index

In [ ]:
population.index

In [ ]:
population['Belgium']

11.3

In [ ]:
population.values

In [ ]:
population/100

In [ ]:
type(population.values)

Accessing dataframe variables using the '.' operator

In [ ]:
type(countries.area)

pandas.core.series.Series

In [ ]:
countries.area.values

array([ 30510, 671308, 357050,  41526, 244820])

In [ ]:
type(countries.capital.values)

## Basic Methods

In [ ]:
countries.columns

Index(['country', 'population', 'area', 'capital'], dtype='object')

In [ ]:
countries.dtypes

country        object
population    float64
area            int64
capital        object
dtype: object

In [ ]:
countries.head(3)

country  population    area   capital
0  Belgium        11.3   30510  Brussels
1   France        64.3  671308     Paris
2  Germany        81.3  357050    Berlin

In [ ]:
countries.describe()

population           area
count    5.000000       5.000000
mean    47.740000  269042.800000
std     31.519645  264012.827994
min     11.300000   30510.000000
25%     16.900000   41526.000000
50%     64.300000  244820.000000
75%     64.900000  357050.000000
max     81.300000  671308.000000

In [ ]:
countries.values

In [ ]:
countries.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
country       5 non-null object
population    5 non-null float64
area          5 non-null int64
capital       5 non-null object
dtypes: float64(1), int64(1), object(2)
memory usage: 288.0+ bytes


In [ ]:
countries.capital.value_counts()

In [ ]:
population

In [ ]:
population.reset_index()

index     0
0         Germany  81.3
1         Belgium  11.3
2          France  64.3
3  United Kingdom  64.9
4     Netherlands  16.9

In [ ]:
type(population.reset_index())

In [ ]:
countries.capital.value_counts().reset_index()

## Selecting and Filtering Data

<div class="alert alert-warning">
<b>ATTENTION!</b>: <br><br>

One of pandas' basic features is the labeling of rows and columns, but this makes indexing also a bit more complex compared to numpy. <br><br> We now have to distuinguish between:

 <ul>
  <li>selection by **label**</li>
  <li>selection by **position**</li>
</ul>
</div>

In [ ]:
df = pd.read_csv("train.csv")

FileNotFoundError: ignored

In [ ]:
df.head()

### `data[]` provides some convenience shortcuts 

Selecting a single column

In [ ]:
df['Pclass']  # Can also use df.Pclass

Selecting multiple columns

In [ ]:
df[  ['Pclass','Sex']   ]

Keep in mind that when we select more than one column, the output is DataFrame and not a series. Hence the difference in formatting of the two outputs above





We can also use this syntax to select specific rows

In [ ]:
df[3:5]

### Systematic indexing with `loc` and `iloc`

When using `[]` like above, you can only select from one axis at once (rows or columns, not both). For more advanced indexing, you have some extra attributes:
    
* `loc`: selection by label
* `iloc`: selection by position

These methods index the different dimensions of the frame:

* `df.loc[row_indexer, column_indexer]`
* `df.iloc[row_indexer, column_indexer]`

**As long as the dataframe has no defined indices, loc can do the job of iloc**

In [ ]:
df.loc[4,'Fare']

In [ ]:
df.loc[df.Sex=='female']

In [ ]:
df.loc[df.Sex=='female','Fare']

In [ ]:
df.loc[df.Sex=='female',['Fare','Name','Sex']]

In [ ]:
df.loc[df.Sex=='female'][['Fare','Name','Sex']]

iloc is based on the position of the elements

In [ ]:
df.iloc[4]

In [ ]:
df.iloc[5:7]

In [ ]:
df.iloc[5:7,'Fare']

In [ ]:
df.iloc[5:7]['Fare']

In [ ]:
df.iloc[[1,2,3,8]]

In [ ]:
df.loc[[1,2,3,8]]

In [ ]:
population

In [ ]:
population.loc[0]

The different indexing methods can also be used to assign data:

In [ ]:
df2 = df.copy()

df2.loc[0,'Fare'] = -100.0

In [ ]:
df2.head()

## Creating New Variables

In [ ]:
countries['newVar'] = [1,2,3,4,5]                   #Basic assignment
countries

country  population    area    capital  newVar
0         Belgium        11.3   30510   Brussels       1
1          France        64.3  671308      Paris       2
2         Germany        81.3  357050     Berlin       3
3     Netherlands        16.9   41526  Amsterdam       4
4  United Kingdom        64.9  244820     London       5

In [ ]:
countries['newVar'] = countries.population * 2  + countries.area**0.5   #Using existing columns
countries

country  population    area    capital      newVar
0         Belgium        11.3   30510   Brussels  197.271120
1          France        64.3  671308      Paris  947.933876
2         Germany        81.3  357050     Berlin  760.136610
3     Netherlands        16.9   41526  Amsterdam  237.579292
4  United Kingdom        64.9  244820     London  624.592886

### Using apply

Apply is a very powerful method which can be used for making major data manipulation tasks

In [ ]:
countries['capital_upper'] = countries['capital'].apply(lambda x : x.upper())
countries

country  population    area    capital      newVar capital_upper
0         Belgium        11.3   30510   Brussels  197.271120      BRUSSELS
1          France        64.3  671308      Paris  947.933876         PARIS
2         Germany        81.3  357050     Berlin  760.136610        BERLIN
3     Netherlands        16.9   41526  Amsterdam  237.579292     AMSTERDAM
4  United Kingdom        64.9  244820     London  624.592886        LONDON

In [ ]:
def ageBucket(x):
    if x<18:
        return "A. <18"
    elif x<25:
        return "B. 18-25"
    elif x<45:
        return "C. 25-45"
    else:
        return "D. >45"
        

Apply can be used on a single column (Series object)

In [ ]:
df['AgeBucket'] = df['Age'].apply(lambda x : ageBucket(x))
df.head()

It can also be used on an entire dataframe

In [ ]:
df['AgeBucket2'] = df.apply(lambda x : ageBucket(x['Age']),axis=1)
df.head()

Other derivative methods that you can look into : `map` and `applymap`

## Groupby Operations

### Some 'theory': the groupby operation (split-apply-combine)

The "group by" concept: we want to **apply the same function on subsets of your dataframe, based on some key to split the dataframe in subsets**

This operation is also referred to as the "split-apply-combine" operation, involving the following steps:

* **Splitting** the data into groups based on some criteria
* **Applying** a function to each group independently
* **Combining** the results into a data structure

<img src="pandas-tutorial-master/img/splitApplyCombine.png">

Similar to SQL `GROUP BY`

In [ ]:
df.groupby('Sex')

In [ ]:
df.groupby("Sex").mean()

In [ ]:
df.groupby('Sex').max()

In [ ]:
def getRange(x):
    
    minVal = np.min(x.Fare)
    maxVal = np.max(x.Fare)
    
    return maxVal - minVal


df.groupby('Pclass').apply(lambda x : getRange(x))

Grouping on multiple columns

In [ ]:
df.groupby(['Sex','Pclass']).mean()

In [ ]:
df.groupby(['Sex','Pclass'])['Age'].mean()

In [ ]:
df.groupby('Sex').agg({'PassengerId':'min', 'Age':'max','Fare':'sum'})

## Merge Operations

Merging with Pandas works pretty much the same as SQL. There are four merge methods:
1. Left
2. Right
3. Inner 
4. Outer

Basic syntax : pd.merge(left_dataframe, right_dataframe, left_on="some_column", right_on="some_column", how="left|right|inner|outer)`

In [ ]:
population = pd.DataFrame({'country': ['Germany', 'Belgium', 'France', 
                        'United Kingdom', 'United States'],'population': [81.3, 11.3, 64.3, 64.9, 65.9]})

countries = pd.DataFrame({'country': ['Belgium', 'France', 'Germany', 'Netherlands', 'United Kingdom'],
        'population': [11.3, 64.3, 81.3, 16.9, 64.9],
        'area': [30510, 671308, 357050, 41526, 244820],
        'capital': ['Brussels', 'Paris', 'Berlin', 'Amsterdam', 'London']})

In [ ]:
population

country  population
0         Germany        81.3
1         Belgium        11.3
2          France        64.3
3  United Kingdom        64.9
4   United States        65.9

In [ ]:
countries

country  population    area    capital
0         Belgium        11.3   30510   Brussels
1          France        64.3  671308      Paris
2         Germany        81.3  357050     Berlin
3     Netherlands        16.9   41526  Amsterdam
4  United Kingdom        64.9  244820     London

In a Left Merge we are mostly concerned with data on the LEFT side but we would like to add data from 
the RIGHT side if it has some of the same countries in this case.

In [ ]:
pd.merge(left=population, right=countries, on="country", how="left")

country  population_x  population_y      area   capital
0         Germany          81.3          81.3  357050.0    Berlin
1         Belgium          11.3          11.3   30510.0  Brussels
2          France          64.3          64.3  671308.0     Paris
3  United Kingdom          64.9          64.9  244820.0    London
4   United States          65.9           NaN       NaN       NaN

In a Right Merge we are mostly concerned with data on the RIGHT side but we would like to add data from 
the LEFT side if it has some of the same countries in this case.

In [ ]:
pd.merge(left=population, right=countries, on="country", how="right")

country  population_x  population_y    area    capital
0         Germany          81.3          81.3  357050     Berlin
1         Belgium          11.3          11.3   30510   Brussels
2          France          64.3          64.3  671308      Paris
3  United Kingdom          64.9          64.9  244820     London
4     Netherlands           NaN          16.9   41526  Amsterdam

With an Inner Merge, we chop up both dataframes and only glue the stuff that matches. If a country isn't in both 
dataframes, we don't keep it and we don't add NaN's. If no type of join is mentioned, then inner join is the 
default join. 

In [ ]:
pd.merge(left=population, right=countries,on ='country')

country  population_x  population_y    area   capital
0         Germany          81.3          81.3  357050    Berlin
1         Belgium          11.3          11.3   30510  Brussels
2          France          64.3          64.3  671308     Paris
3  United Kingdom          64.9          64.9  244820    London

In [ ]:
pd.merge(left=population, right=countries,on ='country', how = "inner")

With an Outer Merge, we chop up both dataframes and keep everything from both sides. Then we toss in NaN's to fill
any blanks.

In [ ]:
pd.merge(left=population, right=countries,on ='country', how = "outer")

country  population_x  population_y      area    capital
0         Germany          81.3          81.3  357050.0     Berlin
1         Belgium          11.3          11.3   30510.0   Brussels
2          France          64.3          64.3  671308.0      Paris
3  United Kingdom          64.9          64.9  244820.0     London
4   United States          65.9           NaN       NaN        NaN
5     Netherlands           NaN          16.9   41526.0  Amsterdam

## Reading Files

In [ ]:
sales_data = pd.read_csv('pandas-tutorial-master/data/blooth_sales_data.csv')

In [ ]:
sales_data.head(5)

In [ ]:
# header = 0 denotes the first line of data. If nothing is mentioned about header, then header = 0 is default.
sales_data2 = pd.read_csv('pandas-tutorial-master/data/blooth_sales_data.csv', header = 0)

In [ ]:
sales_data2.head(5)

In [ ]:
sales_data3 = pd.read_csv('pandas-tutorial-master/data/blooth_sales_data.csv', header = None)
sales_data3.head(5)

In [ ]:
sales_data = pd.read_csv('pandas-tutorial-master/data/blooth_sales_data.csv', usecols=['name', 'birthday'])
sales_data.head(5)

In [ ]:
sales_data = pd.read_csv('pandas-tutorial-master/data/blooth_sales_data.csv', header= None, skiprows=2)
sales_data.columns= ['name', 'birthday','customer','orderadate','product','units','unitprice']
sales_data.head(2)

In [ ]:
# The date parse is US datew friendly! MM/DD/YYYY


sales_data = pd.read_csv('pandas-tutorial-master/data/blooth_sales_data.csv',parse_dates=['birthday', 'orderdate'])
sales_data.head(2)                     

In [ ]:
# To use the more common international format for sure, add 'dayfirst=True'
sales_data = pd.read_csv('pandas-tutorial-master/data/blooth_sales_data.csv',parse_dates=['birthday', 'orderdate'], dayfirst=True)
sales_data.head(2) 

In [ ]:
sales_data.dtypes

In [ ]:
sales_data['modified_orderdate'] = sales_data['orderdate'].apply(lambda x: "%d/%d/%d" % (x.day, x.month, x.year))
sales_data.head(4)

In [ ]:
sales_data.dtypes

In [ ]:
sales_data['Hour'] = sales_data['orderdate'].apply(lambda x: "%d" % (x.hour))
sales_data.head(4)

In [ ]:
sales_data["modified_orderdate"]= pd.to_datetime(sales_data["modified_orderdate"])
sales_data.head(4)
sales_data.dtypes

In [ ]:
sales_data['birth_month'] = sales_data['birthday'].dt.month
sales_data.head(4)

In [ ]:
sales_data_json = pd.read_json('pandas-tutorial-master/data/blooth_sales_data.json')
sales_data_json.head(5)

## Missing Data
How to handle missing data (NaN's)? Most common commands used are fillna and dropna. 

In [ ]:
missing_df = pd.DataFrame(np.random.randn(5, 3), index=['a', 'c', 'e', 'f', 'h'],columns=['one', 'two', 'three'])
missing_df['four'] = 'bar'
missing_df['five'] = missing_df['one'] > 0
missing_df.loc[['a','c','h'],['one','four']] = np.nan
missing_df

In [ ]:
# fillna replaces NA/NAN values with the given value in the command.
missing_df.fillna(0)

In [ ]:
missing_df['one'].fillna('missing')

Dropna is used to drop the rows or columns with NA/NAN values.
<br>
'axis' argument determines if rows or columns which contain missing values are removed.
<br>
'axis =0': Drop rows which contain missing values. 
<br>
'axis =1': Drop columns which contain missing value.
<br>


'how' argument determines if row or column is removed from DataFrame, when we have at least one NA or all NA.
<br>
‘how = any’ : If any NA values are present, drop that row or column. (default)
<br>
‘how = all’ : If all values are NA, drop that row or column.
<br>

In [ ]:
missing_df.dropna(axis=0)

In [ ]:
missing_df.dropna(axis=1)

In [ ]:
missing_df['six'] = np.nan
missing_df

In [ ]:
missing_df.dropna(axis=1, how = 'all')

In [ ]:
#dropping rows only where some columns are missing
missing_df.dropna(subset = ['one', 'two', 'four'])

In [ ]:
df.head()

# Exercises

## Titanic

In [ ]:
df.head()

Calculate the number of passengers with Pclass = 3

Compute the percentage of passengers that survived

How many children below the age of 18?

Whats the ratio of male and female passengers?

Between the two genders, whats the ratio of passengers that survived?

Create a new variable which has 0 for male and 1 for female. Name this variable **LabelEncode_Sex**

Create a variable that takes the value of 1 when Pclass is 1 and 0 otherwise. Create similar variables for when Pclass has a value of 2 and 3.

Name these variables **OHE_PClass1, OHE_PClass2, OHE_PClass3** respectively 

Calculate the mean fare for all samples with an odd index

Create a new variable which stores the last name of passengers

Calculate the number of unique families ( based on last names)

Create a variable that indicates the **size of the family** for each passenger. *Family size is the number of passengers with the same family name*

#### Fare by Cabin Index

All cabin numbers begin with a letter. We hypothesize that this first letter actually has a significance. So create a new variable that stores the first letter of the cabin variable. Call this **CabinIndex**.

NOTE : The cabin variable has missing values. Also check for the data type of the Cabin variable.

Once you have created the CabinIndex variable, calculate the mean value of fare for different levels of CabinIndex

## Sales Data

For sales_data, create a variable named mean_units which is the average of all units when the birth month lies between Feb and August.

In [ ]:
sales_data = pd.read_csv('pandas-tutorial-master/data/blooth_sales_data.csv')
sales_data.dtypes
sales_data["birthday"]= pd.to_datetime(sales_data["birthday"])
sales_data_mid = sales_data[((sales_data['birthday'].dt.month > 2) & (sales_data['birthday'].dt.month <8 ))]
mean_units =sales_data_mid["units"].mean()
mean_units

Create a new column in sales_data titled 'order_minutes' and for each row, store the minutes from orderdate 

In [ ]:
sales_data["orderdate"]= pd.to_datetime(sales_data["orderdate"])
sales_data['order_minutes'] = sales_data['orderdate'].dt.minute
sales_data.head(2)

For sales_data dataframe, create a dataframe called 'sd_df' to store only those rows where product is 'Harry Potter book'

In [ ]:
sales_data = pd.read_csv('pandas-tutorial-master/data/blooth_sales_data.csv')
sd_df = sales_data[sales_data["product"] == 'Harry Potter book' ]
sd_df.head(2)

For sales_data, find the data of people who were born before 1980

In [ ]:
sales_data = pd.read_csv('pandas-tutorial-master/data/blooth_sales_data.csv')
sales_data["birthday"]= pd.to_datetime(sales_data["birthday"])
sales_data= sales_data[sales_data['birthday'].dt.year < 1980]
sales_data.head(2)

For sales_data, find the average unitprice for products that were ordered in first week of a month

In [ ]:
sales_data = pd.read_csv('pandas-tutorial-master/data/blooth_sales_data.csv')
sales_data["orderdate"]= pd.to_datetime(sales_data["orderdate"])
sales_data= sales_data[sales_data['orderdate'].dt.day > 8]
sales_data.head(2)

For sales data, display number of units sold for each product

In [ ]:
sales_data.groupby('product')['units'].sum().reset_index()

Create a new column in sales_data and store orderdate in the format mm/dd/yyyy

In [ ]:
sales_data['new_date'] = sales_data['orderdate'].apply(lambda x: "%d/%d/%d" % (x.month, x.day,x.year))
sales_data

## Iris Dataset

In [ ]:
## Loading the dataset

from sklearn.datasets import load_iris
data = load_iris()

In [ ]:
data.data

In [ ]:
data.target

In [ ]:
data.feature_names

In [ ]:
data.target_names

### Exercises

Put together all the components of the data variable into a Pandas DataFrame. *This means putting together the feature and target variables, and adding their names as column names*

In [ ]:
df = pd.DataFrame(data.data, columns = data.feature_names)

df['target'] = data.target

df.head()

Find number of observations in the dataset which belong to class setosa and have a petal length > 3

Find the maximum and minimum values of each of features.

Find the range of value for each of the features

For each of the target classes, find the mean value of each of the independent variables. The mean values should be represented in a table.

**Do not** use for loops. This should be doable in a single line of code